POST http://localhost:8989/api/good
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlNBQ1JFRCJ9.VPCTlJ9rF4yRDl5KBKioAElbn-8ulcrm-OEcVmQESA4
Content-Type: multipart/form-data; boundary=MfnBoundry

--MfnBoundry
Content-Disposition: form-data; name="file2"; filename="Привет.png"
Content-Type: image/png

< C:\ws_1.png
--MfnBoundry--

###
http://localhost:4002/api/media?fileId=8c8f7935ec7a1790aa0bddac95a7a29f