http://localhost:8989/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlNBQ1JFRCJ9.VPCTlJ9rF4yRDl5KBKioAElbn-8ulcrm-OEcVmQESA4

###
PUT http://localhost:8989/user
content-type: application/json

{
  "id" : 1,
  "caption" : "SACRED",
  "description" : "TEST"
}